### ISSUE TITLE
HTML code in extra data is not escaped

### ISSUE THREAD

**Issue by oemmes** [fsuter/devlog#2]
When the extra data contains HTML code it is not escaped, thus leading to a possible XSS vulnerability. Because of that you could also not inspect the the raw content of the extra data in the entry list.

I think this could be fixed either in the EntryRepository when assigning the extra data to the results array by using `htmlspecialchars()` (in `expandEntryData()`), or in the JavaScript code when generating the actual HTML output by replacing the special chars.

**Comment by fsuter** [comment]
Ah, I did not try with HTML data. You're right. I guess acting in `expandEntryData()` is correct indeed.
