### ISSUE TITLE
Wrong logging in AJAX calls

### ISSUE THREAD

**Issue by froemken** [fsuter/devlog#3]
In AJAX calls you often have no pid. So in my case your INSERT query

```
INSERT INTO tx_devlog_domain_model_entry (run_id,sorting,severity,extkey,mes
      sage,location,line,ip,cruser_id,crdate,pid,extra_data) VALUES ('1479296661.5
      82c46954874e6.39534870','0','1','extbase','The singleton \"JWeiland\\Ev
      ents2\\Domain\\Repository\\DayRepository\" needs a prototype in \"
      injectDateTimeUtility\". This is often a bad code smell; often you rath
      er want to inject a singleton.','Container.php','271','::1','0','1479296661'
      ,NULL,'')
```

results in 

```
Column 'pid' cannot be null
```

**Comment by fsuter** [comment]
I stumbled on that one too in the meantime, although in the context of CLI calls. I already resolved it with https://github.com/fsuter/devlog/commit/3821479fa05f9ccaed4e0522a1852623106b0ad8

**Comment by froemken** [comment]
I still have that problem on current master. You will find it here:
```
$pid = 0;
if (TYPO3_MODE === 'FE') {
            $pid = $GLOBALS['TSFE']->id;
}
```
In case of AJAX you often does not have a TSFE object. So after that $pid will be NULL.

**Comment by fsuter** [comment]
Ah yes, I see, eID calls. OK, will fix it.

**Comment by fsuter** [comment]
And sorry, I confused pid and ip ;-) Patch and release coming up.
