### ISSUE TITLE
Avoid exception if Database is empty

### ISSUE THREAD

**Issue by benjaminpick** [fsuter/devlog#6]
Hi, I am using typo3_console to re-import the Database from Live into my development environment - so the database is completely empty. This is the Exception I get:

 [ Error ]                                             
 Call to a member function exec_INSERTquery() on null  
 thrown in file /Domain/Repository/EntryRepository.php 
 in line 265                                           
                                                       
Exception trace:
#0 Devlog\Devlog\Domain\Repository\EntryRepository::add()
   /Writer/DatabaseWriter.php:54
#1 Devlog\Devlog\Writer\DatabaseWriter::write()
   /Utility/Logger.php:171
#2 Devlog\Devlog\Utility\Logger::log()
#3 call_user_func_array()
   lasses/Utility/GeneralUtility.php:4388
#4 TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction()
   lasses/Utility/GeneralUtility.php:5207
#5 TYPO3\CMS\Core\Utility\GeneralUtility::devLog()
   e/Classes/Object/Container/Container.php:274
#6 TYPO3\CMS\Extbase\Object\Container\Container::log()
   e/Classes/Object/Container/Container.php:310
#7 TYPO3\CMS\Extbase\Object\Container\Container::getConstructorArguments()
   e/Classes/Object/Container/Container.php:207
#8 TYPO3\CMS\Extbase\Object\Container\Container::instanciateObject()
   e/Classes/Object/Container/Container.php:181
#9 TYPO3\CMS\Extbase\Object\Container\Container::getInstanceInternal()
   e/Classes/Object/Container/Container.php:308
#10 TYPO3\CMS\Extbase\Object\Container\Container::getConstructorArguments()
   e/Classes/Object/Container/Container.php:207
#11 TYPO3\CMS\Extbase\Object\Container\Container::instanciateObject()
   e/Classes/Object/Container/Container.php:181
#12 TYPO3\CMS\Extbase\Object\Container\Container::getInstanceInternal()
   e/Classes/Object/Container/Container.php:241
#13 TYPO3\CMS\Extbase\Object\Container\Container::injectDependencies()
   e/Classes/Object/Container/Container.php:182
#14 TYPO3\CMS\Extbase\Object\Container\Container::getInstanceInternal()
   e/Classes/Object/Container/Container.php:126
#15 TYPO3\CMS\Extbase\Object\Container\Container::getInstance()
   e/Classes/Object/ObjectManager.php:99
#16 TYPO3\CMS\Extbase\Object\ObjectManager::get()
   e/Classes/Mvc/Dispatcher.php:115
#17 TYPO3\CMS\Extbase\Mvc\Dispatcher::resolveController()
   e/Classes/Mvc/Dispatcher.php:84
#18 TYPO3\CMS\Extbase\Mvc\Dispatcher::dispatch()
   Classes/Mvc/Cli/RequestHandler.php:80
#19 Helhum\Typo3Console\Mvc\Cli\RequestHandler::handleRequest()
   Classes/Core/ConsoleBootstrap.php:111
#20 Helhum\Typo3Console\Core\ConsoleBootstrap::run()
   Scripts/typo3cms.php:65
#21 {closure}()
   Scripts/typo3cms.php:66
#22 require()
   Scripts/typo3cms:4

Could you please catch this exception so that the "failing to log something" does not hinder the actual code in executing?

Thanks,
Benjamin

(Using devlog 3.0.2)

**Comment by fsuter** [comment]
Hi Benjamin. Indeed there's no check for the availability of the DB connection in the `DatabaseWriter` class. There used to be a check in older versions of devlog. I will add a method to the `WriterInterface` which will make it possible for each log writer to declare whether it is available or not.

Of course this means that a given writer will be disabled for the whole run, whereas, in your case, the database connection could become available at some point during the process, but I want to avoid the overhead of checking availability upon writing of each entry.

**Comment by fsuter** [comment]
I went a simpler way finally: I just added a check for database availability in the LogRepository, which will eventually to an exception and a deactivation of the database writer if DB is not available.

Do you have the opportunity to check if it works as expected for you? I would gladly have your feedback before doing a release.

**Comment by benjaminpick** [comment]
Yes I will try it. Here is my testing plan:

- Creating a new Typo3 instance
- Install devlog and typo3_console
- Export the database to SQL via typo3_console
- Drop the database and create it anew (so there is a DB but a
completely empty one)
- Import the SQL file into databasebase via typo3_console

**Comment by benjaminpick** [comment]
Yes the import did not raise any exception. Thanks!
